name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
    - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Deploy application to remote virtual machine (VM)
        shell: bash
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
            set -euo pipefail
            REPOSITORY_NAME=$(basename "$GITHUB_REPOSITORY")
            cd ~
            if [ ! -d "$REPOSITORY_NAME" ]; then
              git clone https://github.com/$GITHUB_REPOSITORY.git "$REPOSITORY_NAME"
            fi
            cd "$REPOSITORY_NAME"
            git fetch --all --prune
            git checkout main
            git pull --ff-only
            docker compose build --no-cache
            docker compose up -d --remove-orphans
            docker image prune -f
            docker compose ps

# Script pris de Ibrahim Badri pour tester le déploiement sur VM